<?php

########################################################################
# Extension Manager/Repository config file for ext: "danceclub"
#
# Auto generated by Extbase Kickstarter 2011-04-04
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Dance-Club',
	'description' => 'You can manage the members of a dance-club. You can built dance-couples and track their tournament-results.',
	'category' => 'plugin',
	'author' => 'Sven Kalbhenn',
	'author_email' => 'sven@skom.de',
	'author_company' => 'SKom',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>